___

<a href='https://www.instagram.com/lanlearning/'> <img src='../pyimages/logosmall.png' width="100" height="100"/></a>
___
<center>Copyright LanLearning 2020</center>

# Let's Review Numpy!


Below is the list of topics we cover over the first week of camp:
- Part 1: Basic Data Types
- Part 2: Advance Data Types
- Part 3: Functions
- Part 4: Python Processes
- **Part 5: Numpy**

This review notebook is meant to help you practice and reinforce what you have learned about **Numpy** during class.

### New Python Tools

Replace the lines below with your answers to make the sentence correct.

A ```library``` is a resuable piece of code that you can use for your projects or various other needs. It is often included with ```documentation```, which acts as a cheat sheet.

### Numpy

Replace the lines below with your answers to make the sentence correct.

One of the most important features of numpy is its ```element by element``` computation.

Like all libraries, numpy needs to be imported before it can be used. How would you import the numpy library with a nickname of np? Write your answer below.

In [1]:
import numpy as np

Replace the lines below with your answers to make the sentence correct.

When you use a function from numpy, you need to first write ```np```, then type in a ```dot (.)```, and lastly call the function you want to use.

Using functions within the numpy library, find the square root of 7, then round the answer to the nearest hundredths. Print the result.

In [2]:
print(np.round(np.sqrt(7), 2))

2.65


### The Magic of Numpy Arrays

What function from numpy can you use to quickly generate an array of numbers? This function has to have at least 1 parameter, at most 3.

**Answer**: np.arange()

Using your answer above, create an array with the values of (1, 5, 9, 13). Print the array.

In [10]:
arr_1 = np.arange(1, 14, 4)
print(arr_1)

[ 1  5  9 13]


Now, create an array with the values of 0 to 5 (inclusive). Print the array.

In [9]:
arr_2 = np.arange(6)
print(arr_2)

[0 1 2 3 4 5]


What function can you use to turn a list into a numpy array?

**Answer**: np.array()

Create two lists of numbers (of the same length). Convert those lists into numpy arrays. Using numpy's element by element computation, divide the numbers from one of the arrays by the numbers from the other array. Store the resulting array in a variable called ```result_array```. Print ```result_array```.

In [14]:
list_1 = [2, 4, 6, 8]
list_2 = [1, 4, 7, 10]
result_array = np.array(list_1)/np.array(list_2)
print(result_array)

[2.         1.         0.85714286 0.8       ]


Find the square root of all the values in ```result_array```. You can use a calculator to check your answer.

In [15]:
np.sqrt(result_array)

array([1.41421356, 1.        , 0.9258201 , 0.89442719])

### Randomness

If you wanted to simulate the toss of a coin, what function from numpy could you use?

np.random.choice()

Using your answer above, simulate the toss of a coin, say 20 times. If you run it multiple times, you can see that the outcome will vary each time.

In [16]:
np.random.choice(["heads", "tails"], 20)

array(['tails', 'heads', 'tails', 'heads', 'heads', 'heads', 'tails',
       'heads', 'heads', 'heads', 'heads', 'tails', 'heads', 'heads',
       'tails', 'heads', 'heads', 'heads', 'heads', 'tails'], dtype='<U5')

Make up your own scenario in which you want to randomly choose one outcome out of a list of others. (For example, you can't decide when to start your AP summer homework, so you write "Today", "Tomorrow", "Next week", "Next month", and "Never" on slips of paper, put them in a hat, and blindly pull one out. Could you simulate that using your knowledge of Python and numpy?) It can be any situation you want to simulate.

In [37]:
np.random.choice(["Paris", "New York", "Rome", "Berlin", "Tokyo", "Bangkok"]) # spotaneous trip to some famous city

'Rome'

In [43]:
np.random.choice(["Chinese", "Thai", "Italian", "Indian"]) # want to get take out

'Thai'

In [39]:
np.random.choice(["AP Computer Science", "Multimedia Art", "Digital Film", "Beginning Guitar"]) # have to choose an elective for school

'Digital Film'

### Optional

Search up 2 additional mathematical methods from numpy, besides the ones we've already learned and play around with them below. 

In [24]:
np.average(np.array([1, 2, 5, 7, 11])) # np.average(num_array)

5.2

In [25]:
np.median(np.array([2, 3, 5, 6])) # np.median(num_array)

4.0

In [29]:
np.amin(np.array([0, 5, 30, -4, 7])) # np.amin(num_array)

-4

In [30]:
np.amax(np.array([0, 5, 30, -4, 7])) # np.amax(num_array)

30

## Done!! :)

### About this notebook: 
#### Developed by:
* [Kyra Yee](https://www.linkedin.com/in/kyrayee/)


#### Connect with us:
<a href='https://www.linkedin.com/company/lanlearning/'> <img src=https://img.icons8.com/color/48/000000/linkedin.png width="48" height="48" align="left"/></a>

<a href='http://www.instagram.com/lanlearning'> <img src=https://img.icons8.com/fluent/48/000000/instagram-new.png width="48" height="48" align="left"/></a>

<a href='https://www.youtube.com/channel/UC5_yxU9pz4ka7xITJMxO5WA'> <img src=https://img.icons8.com/color/48/000000/youtube-squared.png width="48" height="48" align="left"/></a>

<a href='https://www.github.com/lanlearning/'> <img src=https://img.icons8.com/material-rounded/48/000000/github.png/ width="48" height="48" align="left"/></a>







